d1 done
Gaydar-Kanub/PY-111 pull request #15
Opened 2020-06-08 14:10 UTC by Gaydar-Kanub

test passed successfull

2020-06-22 05:06 UTC, aeksei commented on Tasks/d1_horse.py
> +        except:
Не рекомендовал бы отлавливать общие ошибки. Если не печатаете или не логируете их
Лучше указать специфическую для этого момента ошибку

2020-06-22 05:14 UTC, aeksei requested changes
Нужно разобраться с сортировкой либо обосновать, почему вы так решили сделеать
Мне это не совсем очевидно

---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request". 
После этого нужно будет запросить "re-request review"

2020-06-22 05:14 UTC, aeksei commented on Tasks/d1_horse.py
> +        steps.sort()
не совсем понятно, зачем каждый раз сортировать, это затратно по времени
по мне лучше все шаги проинициализировать, а потом и без try-except и сортировок можно обойтись

2020-06-25 11:44 UTC, Gaydar-Kanub commented on Tasks/d1_horse.py
> +        except:
Спасибо. Прошляпил.

2020-06-25 12:23 UTC, Gaydar-Kanub commented on Tasks/d1_horse.py
> +        steps.sort()
Не знаю как это письменно объяснить. Начну с общего.
За основу взято условие, что конь не ходит "вниз" (назад). Из-за особенностей хода коня при ходе с какой-либо  строки конь никогда не встанет на эту же строку и, исходя из условия, на предыдущую строку. 
Поэтому удобно брать поочередно каждую строку, и для каждой используемой ячейки делать расчет куда еще можно сходить. При этом ВАЖНО строки рассматривать строго по возрастанию.
У меня в очередь обработки добавляются ячейки с указанием строки+1 и строки+2 (особенности хода коня). Для того чтобы это решить, я использовал сортировку. 

Согласен, совсем не лучший вариант.
1) Если уж использовать сортировку, то достаточно сортировки по первому элементу кортежа.
2) Можно использовать две очереди, например:  steps_1 (ячейки в строке+1) и steps_2 (ячейки в строке+2). После опустошения steps_1, записать в нее содержимое step_2. А steps_2 очистить
steps_1, steps_2 = steps_2, []
или
steps_1 = steps_2
steps_2.clear()
3) Как вы и сказали (если я правильно понял), можно вначале создать очередь возможных ходов (список кортежей х и у). Один раз отсортировать. И вычислить значение для каждой ячейки

На мой взгляд вар.1 и вар.2 более наглядны для метода обратного перебора. Это чисто моё внутреннее ощущение.

2020-06-25 12:24 UTC, Gaydar-Kanub commented on Tasks/d1_horse.py
> +        steps.sort()
Скажите по какому варианту сделать и быстро накидаю решение

2020-06-25 12:52 UTC, aeksei commented on Tasks/d1_horse.py
> +        steps.sort()
Мне 3 решенье кажет оптимальным (по большей части, потому что оно мне понятнее остальных)))

когда мы составляем хеш-таблицу ходов у вас это `step_count`, то во-первых мы фиксируем все промежуточные ходы, которые будут совершены в последующие клетки
а гарантированность прохода обеспечивается тем, что шагать назад мы не можем, а только вперед и вправо/влево, поэтому есть слева направо и вверху вниз, то последующие шаги не будут влиять на предыдущие
поэтому и сортировки никакие не нужны, просто последовательно перебираем (0, 0), (0, 1), ... (1, 0), (1, 1), ...

в целом жертвуем памятью, чтобы хранить хеш-таблицу, и не делаем сортировки на каждом шагу

2020-07-06 06:56 UTC, merged