g0 done
Gaydar-Kanub/PY-111 pull request #17
Opened 2020-06-13 07:18 UTC by Gaydar-Kanub

Tests passed successful - classwork

2020-06-22 05:30 UTC, aeksei requested changes
---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request". 
После этого нужно будет запросить "re-request review"

2020-06-22 05:30 UTC, aeksei commented on Tasks/g0_bubble_sort.py
> +                container[i], container[i+1] = container[i+1], container[i]
добавьте ещё проверку, что если так случилось, что в середине сортировки последовательность отсортирована (т.е. на очередном проходе не было переставновки элементов), то можно досрочно прекращать цикл

2020-06-25 14:16 UTC, Gaydar-Kanub commented on Tasks/g0_bubble_sort.py
> +                container[i], container[i+1] = container[i+1], container[i]
Добавил проверку оставшейся части. Но это не экономит время, даже наоборот (ведь каждый раз приходится делать проверку if). Для проверки внес изменения в тесты - увеличил список в сотню раз

2020-06-25 14:18 UTC, Gaydar-Kanub commented on Tasks/g0_bubble_sort.py
> +                container[i], container[i+1] = container[i+1], container[i]
Но при этом сделал небольшую доработку:
С каждым проходом первого цикла уменьшается размер второго цикла на 1 (т.к. в конце уже отсортированные элементы)

2020-06-25 15:56 UTC, aeksei commented on Tasks/g0_bubble_sort.py
> +                container[i], container[i+1] = container[i+1], container[i]
проверка if выполняется за О(1), а вот сортировка пузырьком O(n^2)
на мылах примерах может и не будет видно выигрыша по времени, а вот при большом количестве данных уже будет заметнее

2020-06-25 15:57 UTC, aeksei approved these changes

2020-06-25 16:11 UTC, merged