1) +
Gaydar-Kanub/PY-111 pull request #19
Opened 2020-06-27 07:27 UTC by Gaydar-Kanub

1) +
2)

2020-06-27 07:38 UTC, aeksei commented on Offset.py
> +2)
А итоговая сложность какая получается?
и вставки в список немного другая сложность, Python list, не как классический список работает, а смесь массива и списка
- https://www.yuripetrov.ru/edu/python/ch_06_01.html#id13
- https://wiki.python.org/moin/TimeComplexity

2020-06-27 07:38 UTC, aeksei reviewed
@Gaydar-Kanub

2020-06-27 08:05 UTC, aeksei reviewed
1 и 2 +

2020-06-27 08:33 UTC, aeksei reviewed
3 +

2020-06-27 08:41 UTC, aeksei commented on Offset.py
> +# Но для данного случая я бы выбрал сортировку подсчётом (counting sort)
сортировка подсчетом подходит

2020-06-27 08:41 UTC, aeksei reviewed
7 +

2020-06-27 08:57 UTC, aeksei requested changes

2020-06-27 08:57 UTC, aeksei commented on Offset.py
> +    return True
а здесь же не гарантируется, что заявки отсортированы
если попадется вот такой случай (10, 12), (8, 11)?

2020-06-27 09:48 UTC, aeksei reviewed
Задача с консунсус рядами тоже зачтена

2020-07-01 16:25 UTC, Gaydar-Kanub commented on Offset.py
> +    return True
Подправил решение (переделал полностью)

2020-07-06 06:55 UTC, merged